import type { Metadata } from 'next'
import './globals.css'
import BottomNavBar from '@/components/Navbar/BottomNavBar'

export const metadata: Metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        {children}
        <BottomNavBar />
      </body>
    </html>
  )
}
